#!/bin/bash
# 指导用户如何获取详细的构建日志

echo "=========================================="
echo "获取 GitHub Actions 详细构建日志"
echo "=========================================="
echo ""

echo "请按照以下步骤获取详细的错误信息:"
echo ""

echo "📋 步骤 1: 访问构建页面"
echo "----------------------------------------"
echo "1. 打开浏览器,访问:"
echo "   https://github.com/zmx199299/table-cleaner/actions"
echo ""
echo "2. 找到最近的构建运行(应该是最上面的)"
echo "   标题应该类似: Build and Release"
echo "   提交信息: fix: 将 npm ci 改为 npm install 以避免需要 package-lock.json"
echo ""

echo "📋 步骤 2: 查看失败的作业"
echo "----------------------------------------"
echo "1. 在构建运行页面,你会看到 3 个作业:"
echo "   - Build on ubuntu-latest"
echo "   - Build on windows-latest"
echo "   - Build on macos-latest"
echo ""
echo "2. 点击 'Build on ubuntu-latest' (这个失败了,导致其他被取消)"
echo ""

echo "📋 步骤 3: 查看失败的步骤"
echo "----------------------------------------"
echo "1. 在 'Build on ubuntu-latest' 页面:"
echo "   - 找到显示红色 ❌ 的步骤"
echo "   - 通常会显示某个步骤名称,例如:"
echo "     * Install dependencies"
echo "     * Install Python"
echo "     * Setup Python Virtual Environment"
echo "     * Build application"
echo ""
echo "2. 点击失败的步骤(它会展开显示详细日志)"
echo ""

echo "📋 步骤 4: 复制错误信息"
echo "----------------------------------------"
echo "1. 在展开的日志中,向下滚动到错误部分"
echo "2. 找到以下内容之一:"
echo "   - 红色的错误消息"
echo "   - 包含 'Error:' 的行"
echo "   - 包含 'FAIL' 或 'failed' 的行"
echo "   - 最后一行的错误输出"
echo ""
echo "3. 选择并复制:"
echo "   - 错误消息的完整内容"
echo "   - 或者至少包含错误的 10-20 行日志"
echo ""

echo "📋 步骤 5: 粘贴错误信息"
echo "----------------------------------------"
echo "将复制的错误信息粘贴回对话框,我会帮你分析并修复!"
echo ""

echo "=========================================="
echo "常见的错误示例"
echo "=========================================="
echo ""

echo "❌ 示例 1: npm install 失败"
echo "----------------------------------------"
echo "npm ERR! code E404"
echo "npm ERR! 404 Not Found - GET https://registry.npmjs.org/..."
echo "npm ERR! 404"
echo "npm ERR! Please try running this command again as root/Administrator."
echo ""

echo "❌ 示例 2: Python 安装失败"
echo "----------------------------------------"
echo "Reading package lists... Done"
echo "E: Unable to locate package python3-pip"
echo "Error: Process completed with exit code 100"
echo ""

echo "❌ 示例 3: electron-builder 构建失败"
echo "----------------------------------------"
echo "electron-builder  version=24.13.3"
echo "  building        target=AppImage arch=x64 electron=30.0.0"
echo "Error: ENOENT: no such file or directory, open 'main.js'"
echo ""

echo "❌ 示例 4: 依赖冲突"
echo "----------------------------------------"
echo "npm ERR! code ERESOLVE"
echo "npm ERR! ERESOLVE unable to resolve dependency tree"
echo "npm ERR! While resolving: table-cleaner@1.0.0"
echo "npm ERR! Found: electron@30.0.0"
echo "npm ERR! Could not resolve dependency:"
echo ""

echo "=========================================="
echo "快速提示"
echo "=========================================="
echo ""
echo "📌 如果页面显示 'Process completed with exit code 1'"
echo "   说明某个步骤执行失败,需要查看具体是哪个步骤"
echo ""
echo "📌 如果看到大量日志,使用 Ctrl+F 搜索 'Error' 或 'FAIL'"
echo "   可以快速定位错误信息"
echo ""
echo "📌 如果不确定,可以复制整个失败的步骤日志"
echo "   越多信息越好分析"
echo ""
echo "📌 也可以尝试点击右上角的 'View raw logs'"
echo "   这会显示完整的纯文本日志,更容易复制"
echo ""

echo "=========================================="
echo "等你提供错误信息后,我会立即帮你修复!"
echo "=========================================="
